#title: Your awesome title
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           none
relative_permalinks: true

# Setup
title:               Karmi's Link Blog
tagline:             'Things I want to archive for later'
description:         'Things I want to archive for later'
url:                 https://karmiphuc.github.io
baseurl:             '/link-blog'
paginate:            5

# About/contact
author:
  name:              Karmi Phúc
  url:               http://karmiphuc.com
  email:             karmiphuc@gmail.com

# Custom vars
version:             1.0.0
